# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/jenkins-pipeline ]
  pull_request:
    branches: [ feature/jenkins-pipeline ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Go to the repository
        run: cd /home/fyprobotics/Desktop/iw.hub && git checkout feature/jenkins-pipeline && git pull
      - name: Copy the directory into a temporary one
        run: cp -R /home/fyprobotics/Desktop/iw.hub /home/fyprobotics/Desktop/iw.hub-temp
      - name: Run the Jenkins Pipeline
        run: cd /home/fyprobotics/Desktop/jenkinsRunner && ./runner/bin/jenkinsfile-runner -p ./jenkins_home/plugins -w ./jenkins -f /home/fyprobotics/Desktop/iw.hub/jenkins
      - name: Remove the temporary directory
        run: rm -r /home/fyprobotics/Desktop/iw.hub-temp
      # Runs a set of commands using the runners shell
